### PR TITLE
Improve parsing speed by manual implementing xml.Unmarshaller for some types.

### PR DESCRIPTION
**Pull request by xakep666**
Implementation made for types representing row and shared string.
I've got around 25% speed improvement. Approaches taken from https://stackoverflow.com/a/61858457

### CODE REVIEW

**Comment by dglsparsons** [comment]
Hi @xakep666. Thanks for submitting this. Are you able to also provide the benchmark you used to measure the 25% speed improvement? I'm tempted to benchmark this on a second machine to check if it holds up before giving it a more thorough checking through, if that's okay with you?

**Comment by xakep666** [comment]
@dglsparsons Benchmark code:
```go
package xlsxreader

import (
	"io/ioutil"
	"testing"

	"github.com/stretchr/testify/require"
)

func BenchmarkOpenReadFile(b *testing.B) {
	bytes, err := ioutil.ReadFile("big_file.xlsx")
	require.NoError(b, err)

	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		f, err := NewReader(bytes)
		require.NoError(b, err)
		for range f.ReadRows(f.Sheets[0]) {}
	}
}
```
I've used same file as for shared strings impact measurements.
To minimize IO impact I've used ReadAll+NewReader.

Results:
* basic:
```
cpu: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
BenchmarkOpenReadFile
BenchmarkOpenReadFile-8   	       1	7343979346 ns/op	1411359160 B/op	34380580 allocs/op
```

* xml.Unmarshaller implemented:
```
cpu: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
BenchmarkOpenReadFile
BenchmarkOpenReadFile-8   	       1	5551259414 ns/op	1244998072 B/op	27808854 allocs/op
```

**Comment by dglsparsons** [comment]
Thanks for this - I've added an extra commit just fixing some linting issues / removing some extra allocations and making the `UnmarshalXML` functions package private. 

It looks like a really big improvement, and IMO, the code is pretty readable. So I'm in favour of this.

**Review by dglsparsons — DISMISSED** [review]

**Comment by dglsparsons** [comment]
CC @AndyThurgood

**Review by dglsparsons — APPROVED** [review]

**Comment by xakep666** [comment]
> Thanks for this - I've added an extra commit just fixing some linting issues / removing some extra allocations and making the `UnmarshalXML` functions package private.
> 
> It looks like a really big improvement, and IMO, the code is pretty readable. So I'm in favour of this.

Probably it's not a last improvement. I found approach with replacing `decoder.Token()` with `decoder.RawToken()` but at first glance it adds even more boilerplate and donesn't make significant performance improvenent. Maybe later I'll try to measure this.

**Comment by xakep666** [comment]
Please tag a new release (I think patch bump is enough) after merge.

**Comment by xakep666** [comment]
@AndyThurgood can we get this merged?

**Review by AndyThurgood — APPROVED** [review]

**Pull request merged**
